### ISSUE TITLE
我是原应用数据维护者

### ISSUE THREAD

**Issue by brentybh** [iovxw/biying#3]
我是原应用的数据维护者，本来只有网页版，和另外一个开发者合作出的 UWP 应用。
这是直接使用了我的数据库和图片服务器吗？

**Comment by iovxw** [comment]
你好，是的

非常抱歉没有事先联系，因为这个项目还没有完成，本来准备写完后再发信询问是否可以发布（目前源码中未包含 LeanCloud Key，所以无法编译，只有 CI 自动生成的 AppImage），但是最近比较忙，坑一直没填

现在程序中只在设置页面底部注明了数据来源 https://github.com/iovxw/biying/blob/master/assets/SettingPage.qml#L246
，请问我可以这样发布吗？或者需作何修改？

如不允许我会立即删除

**Comment by brentybh** [comment]
不会，谢谢你做的应用，只要应用保持开源免费就 OK
LeanCloud 前几天[域名被封了](https://blog.avoscloud.com/6841/)，
我已经申请了自定义 API 域名 leanapi.bohan.co
源码里把 leancloud.cn 换成这个域名就好了
如果你愿意的话，我也可以把你拉进 LeanCloud 应用的团队里

**Comment by brentybh** [comment]
网站源码 https://github.com/brentybh/homepage-fetcher
和 LeanCloud 云函数更新源码 https://github.com/brentybh/homepage-fetcher
都放出来了，之前因为仓库里有 app key 就一直是私有，现在去掉了
（虽然 app key 早已经被 uwp 开发者传上来了 233）

**Comment by iovxw** [comment]
谢谢，已更新
团队就不用了，没时间大概不能帮上什么忙，应用会一直保持开源的
还有网站做的很棒 :+1:
